---
title: "Final - Code Part 1"
author: "Sacha Robbins"
date: "May 12, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = F, message = FALSE, warning = FALSE )
# --
# data visualization
library(ggplot2) 
library(GGally)
library(gridExtra)
library(knitr)
library(kableExtra)
# --
library(tidyverse) # data science package
library(MASS) # for glm.nb and other functions and datasets
library(survival) # survival analysis package
library(splines) # for ns function
library(gee) # generalized estimation equation solver
library(nlme) # for linear mixed effects models
library(MCMCpack)
library(rjags)
library(rmeta) # forestplots
# --
source("https://www.ics.uci.edu/~dgillen/STAT212/Handouts/Stat212Functions.R")
# --
# Extras
library(latex2exp) # math expressions in plots
library( mvtnorm ) # in order to use rmvnorm
```

```{r load data}
bc <- read.csv("https://www.ics.uci.edu/~dgillen/STAT212/Data/bcarotene_212final2018.csv", header = TRUE)
attach(bc)
```

# Does beta-carotene supplementation impact serum beta-carotene levels over time?

```{r first model clean-up}
bc2 <- bc[, c("X", "ptid", "month", "bcarot", "dose")] %>% 
  filter( month < 10)

colnames(bc2)[3] <- "time"

# change dose to be indicator var
bc2$factor.dose <- rep(0, nrow(bc2))
for(i in 1:nrow(bc2)){
  if(bc2$dose[i] > 0) bc2$factor.dose[i] <- 1
}

# calculate baseline measurement pre-treatment/placebo
bc.base <- bc2 %>% 
  filter( time >= 0 & time < 4) %>% 
  group_by(ptid) %>% 
  summarise(mean(bcarot, na.rm = T))

bc.base <- as.data.frame(bc.base)

# insert baseline measurement in place of bcarot for month "0" 
n.obs <- unlist( lapply( split( bc2$ptid, bc2$ptid ), length ) )
u.id <- unique(bc2$ptid)

bc2$base <- rep(0, nrow(bc2))
for(j in 1:length(u.id)){
  temp <- bc2 %>% filter(ptid == u.id[j])
  id <- which(bc.base[,1]==u.id[j])
  row <- which(bc2$X == temp[1,1])
  bc2$base[row:(row+nrow(temp)-1)] <- rep(bc.base[id,2],nrow(temp))
}

# get rid of months 0-3
bc2 <- bc2 %>% filter(time != 0 & time != 1 & time != 2 & time != 3 )

# re-number time 4-9 as 1-6
for(i in 1:nrow(bc2)){
  if(bc2$time[i] == 4) bc2$time[i] <- 1 
  if(bc2$time[i] == 5) bc2$time[i] <- 2 
  if(bc2$time[i] == 6) bc2$time[i] <- 3 
  if(bc2$time[i] == 7) bc2$time[i] <- 4 
  if(bc2$time[i] == 8) bc2$time[i] <- 5 
  if(bc2$time[i] == 9) bc2$time[i] <- 6 
}

sapply(bc2, function(x) sum(is.na(x)))
bc2[which(is.na(bc2$bcarot)),]

# replace patient 31 missing value with average of other bcarot values
# seems to be a good fit to the trend
temp <- bc2 %>% filter(ptid == 31)
bc2[which(is.na(bc2$bcarot)),"bcarot"] <- mean(as.numeric(temp$bcarot), na.rm = T)

dput(temp, "patient31")

# now we have no missing values!
```

```{r first model EDA}
# 81% get treatment and 19% get placebo
p.grp <- bc2 %>% filter(factor.dose == 0)
t.grp <- bc2 %>% filter(factor.dose == 1)

# Histogram of Mean Response Stratified by Placebo and Treatment Group
hist1 <- ggplot() + 
  geom_histogram(data = p.grp, aes(x=bcarot), color = "red", fill = "pink") + 
  geom_histogram(data = t.grp, aes(x=bcarot), color = "blue", fill = "blue", alpha = 0.5) + ggtitle("") + xlab("Serum BC (ug/mL)") + ylab("Count") + geom_text(aes(x=500, y=25), color="red", label = "Placebo Group") + geom_text(aes(x=2250, y=25), color="blue", label = "Treatment Group")

hist2 <- ggplot() + 
  geom_histogram(data = p.grp %>% filter(ptid != 57), aes(x=bcarot), color = "red", fill = "pink") + 
  geom_histogram(data = t.grp %>% filter(ptid != 57), aes(x=bcarot), color = "blue", fill = "blue", alpha = 0.5) + ggtitle("Without Patient 57") + xlab("Serum BC (ug/mL)") + ylab("Count") + geom_text(aes(x=500, y=25), color="red", label = "Placebo Group") + geom_text(aes(x=2250, y=25), color="blue", label = "Treatment Group")

# Spaghetti Plot of Mean Response Over Time Stratified by Placebo and Treatment Groups
spag1 <- ggplot() +
  geom_line(data = p.grp, aes(x=time, y=bcarot, group=ptid), color="red", alpha = 0.6) + 
  geom_line(data = t.grp, aes(x=time, y=bcarot, group=ptid), color="blue", alpha = 0.6) + ggtitle("") + ylab("Serum BC (ug/mL)") + xlab("Time During Treatment Phase (months)") + geom_text(aes(x=5, y=2250), color="red", label = "Placebo Group") + geom_text(aes(x=5, y=2750), color="blue", label = "Treatment Group")

# w/o patient 57
spag2 <- ggplot() +
  geom_line(data = p.grp %>% filter(ptid != 57), aes(x=time, y=bcarot, group=ptid), color="red", alpha = 0.6) + 
  geom_line(data = t.grp %>% filter(ptid != 57), aes(x=time, y=bcarot, group=ptid), color="blue", alpha = 0.6) + ggtitle("Without Patient 57") + ylab("Serum BC (ug/mL)") + xlab("Time During Treatment Phase (months)") + geom_text(aes(x=5, y=2250), color="red", label = "Placebo Group") + geom_text(aes(x=5, y=2750), color="blue", label = "Treatment Group")

grid.arrange(hist1, hist2, spag1, spag2, ncol=2)
ggsave("plots.png", arrangeGrob(hist1, hist2, spag1, spag2))

```

```{r covariance EDA}
# ONLY MONTHS 4-9 (TREATMENT MONTHS)
fit <- lm( bcarot ~ time, data=bc2 )
resids <- bc2$bcarot - fitted( fit )

# variogram
out <- lda.variogram( id=bc2$ptid, y=resids, x=bc2$time )
dr <- out$delta.y
dt <- out$delta.x
var.est <- var( resids, na.rm = T )

variogram <- ggplot() +
  geom_point(aes(x=dt, y=dr), pch = ".") + 
  geom_smooth(aes(x=dt, y=dr)) + ylim(0, 1.2*var.est) + geom_hline(yintercept=var.est) + 
  ggtitle("Variogram of Plasma BC Levels during Treatment Phase") + xlab("Delta Time") + ylab("Delta Residuals")

ggsave("var.png", variogram)

# There doesn't seem to be much of a serial process; everything points to exchangeable covariance structure.
# covariance summaries / pairwise residual scatterplots

nobs <- length( bc2$bcarot )
nsubjects <- length( table( bc2$ptid ) )
rmat <- matrix( NA, nsubjects, 6 )
ycat <- c( 1,2,3,4,5,6 )
nj <- unlist( lapply( split( bc2$ptid, bc2$ptid ), length ) )
mymin <- function(x){ ifelse( sum( !is.na(x) )==0, NA, min(x, na.rm=TRUE ) ) }
for( j in 1:6 ){
	legal <- ( bc2$time >= ycat[j]-0.5 )&( bc2$time < ycat[j]+0.5 )
	jtime <- bc2$time + 0.01*rnorm(nobs)
	t0 <- unlist( lapply( split( abs(jtime - ycat[j]) , bc2$ptid ), min ) )
	tj <- rep( t0, nj )
	keep <- ( abs( jtime - ycat[j] )==tj ) & ( legal )
	yj <- rep( NA, nobs )
	yj[keep] <- resids[keep]
	yj <- unlist( lapply( split( yj, bc2$ptid ), mymin ) )
	rmat[ , j ] <- yj
}
dimnames( rmat ) <- list( NULL, paste("Month",c(4:9)) )

pairs <- ggpairs(as.data.frame(rmat))
ggsave("pairs.png", pairs)

# Pairwise Residual Scatterplot reinforces that there is correlation between observations and it seems quite consistent --> exchangeable covariance
#
# covariance matrix / empirical estimate of covariance/correlation matrix
#
cmat <- matrix( 0, 6, 6 )
nmat <- matrix( 0, 6, 6 )
#
for( j in 1:6 ){
  for( k in j:6 ){
	njk <- sum( !is.na( rmat[,j]*rmat[,k] ) )
	sjk <- sum( rmat[,j]*rmat[,k], na.rm=T )/njk
	cmat[j,k] <- sjk
	nmat[j,k] <- njk
  }
}
vvec <- diag(cmat)
cormat <- cmat/( outer( sqrt(vvec), sqrt(vvec) ) )
# Number of observations per month seems balanced; tells us we can trust our empirical covariance and correlation matrices --> exchangeable
```

```{r investigate random effects}
# fits a lm for each subject
# outputs intercept and slopes
indiv.lm <- lmList( bcarot ~ time | ptid , data=bc2 )

path <- "~/Desktop/212/Final/"
jpeg( file=paste( path, "randeffplot.jpg", sep="" ))
plot( intervals( indiv.lm ) )
dev.off()

# more evidence of random intercepts; random slopes don't seem present.
```

```{r first model fit a model}
# check nobs per subject
n.obs <- unlist( lapply( split( bc2$ptid, bc2$ptid ), length ) )
table(n.obs)
# get rid of subject 44 with < 3 obs
bc2 <- bc2 %>% filter(ptid != 44)

# mean-center baseline measurement (base) in order to get a more interpretable intercept
bc2$mc.base <- bc2$base - mean(bc2$base)

# now we have 44 subjects
# fit the model
fit <- gee(bcarot ~  factor.dose + mc.base + time + time*factor.dose, id = ptid, data = bc2, corstr = "exchangeable")
table1 <- summary(fit)$coeff[,c(1,4)]
row.names(table1) <- c("Intercept", "Tx", "Mc.Base", "Month", "Tx:Month")

# fit the model w/o patient 57
fit2 <- gee(bcarot ~ factor.dose + mc.base + time + time*factor.dose, id = ptid, data = bc2 %>% filter(ptid != 57), corstr = "exchangeable")
table2 <- summary(fit2)$coeff[,c(1,4)]
row.names(table2) <- c("Intercept", "Tx", "Mc.Base", "Month", "Tx:Month")
colnames(table2) <- c("Est (w/o 57)", "Robust SE (w/o 57)")

table <- cbind(table1[,1], table2[,1], table1[,2], table2[,2])
colnames(table) <- c("Estimates","Est (w/o 57)", "Robust SE","Robust SE (w/o 57)")

dput(table, "output")

res1 <- ggplot() +
  geom_point(aes(x=fit$fitted, y=fit$residuals)) + ggtitle("Residuals vs. Fitted Values") + geom_hline(yintercept = 0) + xlab("Fitted Values") + ylab("Residuals")

res2 <- ggplot() +
  geom_point(aes(x=fit2$fitted, y=fit2$residuals)) + ggtitle("Without Patient 57") + geom_hline(yintercept = 0) + xlab("Fitted Values") + ylab("Residuals")

ggsave("resplots.png", arrangeGrob(res1, res2))
```


## Stratify by doses

```{r stratify by doses and EDA}
grp0 <- bc %>% filter(dose == 0)
grp15 <- bc %>% filter(dose == 15)
grp30 <- bc %>% filter(dose == 30)
grp45 <- bc %>% filter(dose == 45)
grp60 <- bc %>% filter(dose == 60)

# spaghetti plots

ggplot() +
  geom_line(data = grp0, aes(x=month, y=bcarot, group=ptid), color="pink") + 
  geom_line(data = grp15, aes(x=month, y=bcarot, group=ptid), color="red") + 
  geom_line(data = grp30, aes(x=month, y=bcarot, group=ptid), color="orange") + 
  geom_line(data = grp45, aes(x=month, y=bcarot, group=ptid), color="yellow") + 
  geom_line(data = grp60, aes(x=month, y=bcarot, group=ptid), color="green")  

# w/o patient 57

grp0 <- bc %>% filter(ptid != 57) %>% filter(dose == 0)
grp15 <- bc %>% filter(ptid != 57) %>% filter(dose == 15)
grp30 <- bc %>% filter(ptid != 57) %>% filter(dose == 30)
grp45 <- bc %>% filter(ptid != 57) %>% filter(dose == 45)
grp60 <- bc %>% filter(ptid != 57) %>% filter(dose == 60)

ggplot() +
  geom_line(data = grp0, aes(x=month, y=bcarot, group=ptid), color="pink") + 
  geom_line(data = grp15, aes(x=month, y=bcarot, group=ptid), color="red") + 
  geom_line(data = grp30, aes(x=month, y=bcarot, group=ptid), color="orange") + 
  geom_line(data = grp45, aes(x=month, y=bcarot, group=ptid), color="yellow") + 
  geom_line(data = grp60, aes(x=month, y=bcarot, group=ptid), color="green")  
```

```{r more EDA by doses}
# mean plots
# change dose into a factor
bc$dose <- as.factor(bc$dose)
mean1 <- ggplot(bc %>% filter(dose != 0 & month > 3 & month < 10), aes(x=month, y=bcarot, fill= dose)) +
  geom_point(pch=1) + 
  geom_smooth() + 
  ggtitle("Mean Plot of Data Stratified by Doses of Treatment") + 
  ylab("BC Level") + 
  xlab("Month") 

# w/o patient 57
mean2 <- ggplot(bc %>% filter(dose != 0 & month > 3 & month < 10 & ptid != 57), aes(x=month, y=bcarot, fill= dose)) +
  geom_point(pch=1) + 
  geom_smooth() + 
  ggtitle("Without Patient 57") + 
  ylab("BC Level") + 
  xlab("Month") 

# w/o placebo group since we know that placebo doesn't affect serum beta-carotene levels
mean3 <- ggplot(bc %>% filter(dose != 0 & month >= 4), aes(x=month, y=bcarot, fill= dose)) +
  geom_point(pch=1) + 
  geom_smooth() + 
  ggtitle("Treatment & Post-Treatment Phases without Placebo Group") + 
  ylab("BC Level") + 
  xlab("Month") + 
  geom_vline(xintercept=9)

ggsave("meanplots.png", arrangeGrob(mean2, mean3))

```

## Model Investigating Dose-Dependent Impact

```{r fit model with various dose levels}
# fit the model with factor dose (15,30,45,60)
# we don't need to worry about patient 57, since they were assigned placebo

fit <- gee(bcarot ~ I(dose/15) + mc.base + time + time*I(dose/15), id = ptid, data = bc2 %>% filter(dose != 0), corstr = "exchangeable")
output <- summary(fit)$coeff[,c(1,4)]
row.names(output) <- c("Intercept", "Dose/15", "Mc.Base", "Month", "(Dose/15):Month")

dput(output, "output2")

res1 <- ggplot() +
  geom_point(aes(x=fit$fitted, y=fit$residuals)) + geom_hline(yintercept = 0) + xlab("Fitted Values") + ylab("Residuals")

ggsave("doseresplot.png", res1)
```

## Is there a difference by dose in the rate at which patients return to baseline after ceasing supplementation?

```{r clean up}
bc <- read.csv("https://www.ics.uci.edu/~dgillen/STAT212/Data/bcarotene_212final2018.csv", header = TRUE)
bc3 <- bc[, c("X", "ptid", "month", "bcarot", "dose")]

colnames(bc3)[3] <- "time"

# calculate baseline measurement pre-treatment/placebo
bc.base <- bc3 %>% 
  filter( time >= 0 & time < 4) %>% 
  group_by(ptid) %>% 
  summarise(mean(bcarot, na.rm = T))

bc.base <- as.data.frame(bc.base)

# insert baseline measurement in place of bcarot for month "0" 
n.obs <- unlist( lapply( split( bc3$ptid, bc3$ptid ), length ) )
u.id <- unique(bc3$ptid)

bc3$base <- rep(0, nrow(bc3))
for(j in 1:length(u.id)){
  temp <- bc3 %>% filter(ptid == u.id[j])
  id <- which(bc.base[,1]==u.id[j])
  row <- which(bc3$X == temp[1,1])
  bc3$base[row:(row+nrow(temp)-1)] <- rep(bc.base[id,2],nrow(temp))
}

# get rid of months 0-9
bc3 <- bc3 %>% filter(time > 9)

# re-number time 4-9 as 1-6
for(i in 1:nrow(bc3)){
  if(bc3$time[i] == 10) bc3$time[i] <- 0
  if(bc3$time[i] == 13) bc3$time[i] <- 3
  if(bc3$time[i] == 14) bc3$time[i] <- 4 
  if(bc3$time[i] == 15) bc3$time[i] <- 5 
}

sapply(bc3, function(x) sum(is.na(x)))
# we have no missing values!

# check nobs per subject
n.obs <- unlist( lapply( split( bc3$ptid, bc3$ptid ), length ) )
table(n.obs)

# get rid of subjects 4, 31, and 57 with < 3 obs
bc3 <- bc3 %>% filter(ptid != 4 & ptid != 31 & ptid != 57)

# mean-center baseline measurement (base) in order to get a more interpretable intercept
bc3$mc.base <- bc3$base - mean(bc3$base)
```

```{r EDA covariance}
# ONLY MONTHS 10-15 (Cease-treatment months)
fit <- lm( bcarot ~ time, data=bc3 )
resids <- bc3$bcarot - fitted( fit )

# variogram
out <- lda.variogram( id=bc3$ptid, y=resids, x=bc3$time )
dr <- out$delta.y
dt <- out$delta.x
var.est <- var( resids, na.rm = T )

variogram <- ggplot() +
  geom_point(aes(x=dt, y=dr), pch = ".") + 
  geom_smooth(aes(x=dt, y=dr)) + ylim(0, 1.2*var.est) + geom_hline(yintercept=var.est) + 
  ggtitle("Variogram of Plasma BC Levels during Post-Treatment Phase") + xlab("Delta Time") + ylab("Delta Residuals")

ggsave("var2.png", variogram)

# Small measurement error, large random intercept, and serial process

# covariance summaries / pairwise residual scatterplots

bc3$time2 <- rep(1, nrow(bc3))
# re-number time 0,3,4,5 as 1-4
for(i in 1:nrow(bc3)){
  if(bc3$time[i] == 3) bc3$time2[i] <- 2
  if(bc3$time[i] == 4) bc3$time2[i] <- 3
  if(bc3$time[i] == 5) bc3$time2[i] <- 4
}

nobs <- length( bc3$bcarot )
nsubjects <- length( table( bc3$ptid ) )
rmat <- matrix( NA, nsubjects, 4 )
ycat <- c( 1,2,3,4 )
nj <- unlist( lapply( split( bc3$ptid, bc3$ptid ), length ) )
mymin <- function(x){ ifelse( sum( !is.na(x) )==0, NA, min(x, na.rm=TRUE ) ) }
for( j in 1:4 ){
	legal <- ( bc3$time2 >= ycat[j]-0.5 )&( bc3$time2 < ycat[j]+0.5 )
	jtime <- bc3$time2 + 0.01*rnorm(nobs)
	t0 <- unlist( lapply( split( abs(jtime - ycat[j]) , bc3$ptid ), min ) )
	tj <- rep( t0, nj )
	keep <- ( abs( jtime - ycat[j] )==tj ) & ( legal )
	yj <- rep( NA, nobs )
	yj[keep] <- resids[keep]
	yj <- unlist( lapply( split( yj, bc3$ptid ), mymin ) )
	rmat[ , j ] <- yj
}
dimnames( rmat ) <- list( NULL, paste("Month",c(10,13,14,15)) )

pairs <- ggpairs(as.data.frame(rmat))
ggsave("pairs2.png", pairs)


# It's difficult to discern if there is serial process  in Pairwise Residual Scatterplot

# covariance matrix / empirical estimate of covariance/correlation matrix
cmat <- matrix( 0, 4, 4 )
nmat <- matrix( 0, 4, 4 )
for( j in 1:4 ){
  for( k in j:4 ){
	njk <- sum( !is.na( rmat[,j]*rmat[,k] ) )
	sjk <- sum( rmat[,j]*rmat[,k], na.rm=T )/njk
	cmat[j,k] <- sjk
	nmat[j,k] <- njk
  }
}
vvec <- diag(cmat)
cormat <- cmat/( outer( sqrt(vvec), sqrt(vvec) ) )

# We still can't tell if there is an AR-1 process since n is small. So, let's fit the same model with AR-1 process.
```

```{r fit model AR-1 }
fit3 <- gee(bcarot ~ I(dose/15) + mc.base + time + time*I(dose/15), id = ptid, data = bc3 %>% filter(dose != 0), corstr = "AR-M", Mv=1)
table <- summary(fit3)$coeff[,c(1,4)]
row.names(table) <- c("Intercept", "Dose/15", "Mc.Base", "Month", "(Dose/15):Month")

dput(table, "output3")

res3 <- ggplot() +
  geom_point(aes(x=fit3$fitted, y=fit3$residuals)) + geom_hline(yintercept = 0) + xlab("Fitted Values") + ylab("Residuals")

ggsave("postresplot.png", res3)
```




