---
title: "Final Code Part 2"
author: "Sacha Robbins"
date: "June 10, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set( echo = F, message = FALSE, warning = FALSE )
# --
# data visualization
library(ggplot2) 
library(GGally)
library(gridExtra)
library(knitr)
library(kableExtra)
# --
library(tidyverse) # data science package
library(MASS) # for glm.nb and other functions and datasets
library(survival) # survival analysis package
library(splines) # for ns function
library(gee) # generalized estimation equation solver
library(nlme) # for linear mixed effects models
library(MCMCpack)
library(rjags)
library(rmeta) # forestplots
# --
source("https://www.ics.uci.edu/~dgillen/STAT212/Handouts/Stat212Functions.R")
# --
# Extras
library(latex2exp) # math expressions in plots
library( mvtnorm ) # in order to use rmvnorm
library(leaps) # helpful for prediction modeling
```

```{r load data}
bc <- read.csv("https://www.ics.uci.edu/~dgillen/STAT212/Data/bcarotene_212final2018.csv", header = TRUE)
```


# Question 2 - Quantify whether effect of bc supplementation on serum bc levels over time differs by age, gender, BMI, or cholesterol

```{r EDA pre-treatment of time-invariant covariates}
# isolate all patient info during months 0-3
# take average bcarot measures

bc.sub <- matrix(NA, nrow = length(unique(bc$ptid)), ncol = 6 )
colnames(bc.sub) <- c("ptid", "aver.bcarot", "age", "male", "bmi", "chol")
for(i in 1:length(unique(bc$ptid))){
  temp <- bc %>% filter(ptid == unique(bc$ptid)[i] & month < 4)
  row <- c(temp$ptid[1], mean(temp$bcarot, na.rm = T), temp$age[1], temp$male[1], temp$bmi[1], temp$chol[1]) 
  bc.sub[i,] <- row
}

bc.sub <- as.data.frame(bc.sub)

ggplot() +
  geom_histogram(data = bc.sub %>% filter(male == 1), aes(x=aver.bcarot), color = "blue", fill = "blue", alpha = 0.6) + 
  geom_histogram(data = bc.sub %>% filter(male == 0), aes(x=aver.bcarot), color = "pink", fill = "pink", alpha = 0.6)
# women tend to have higher average beta-carotene than men

ggplot() +
  geom_point(data = bc.sub, aes(x=age, y=aver.bcarot, color=factor(male)), alpha = 0.6)
# doesn't seem to be correlation b/w age and average beta-carotene & even when stratified by gender

bmi.plot <- ggplot() +
  geom_point(data = bc.sub, aes(x=bmi, y=aver.bcarot, color=factor(male)), alpha = 0.8) + 
  labs( x = "Body Mass Index (BMI)", y = "Average Baseline BC Levels", color = "Male \n")
ggsave("bmi.png", bmi.plot)

# there seems to be negative correlation b/w bmi and average beta-carotene! higher BMI --> lower average bc
# seems consistent across gender

ggplot() +
  geom_point(data = bc.sub, aes(x=chol, y=aver.bcarot, color=factor(male)), alpha = 0.6)
# no clear association b/w chol and average bc even when stratified by gender
```

```{r EDA of time-invariant covariates during treatment}

# eliminate vite and dose level; only focus on pre and during tx & those tx
bc.sub <- bc[,-5] %>% filter( month < 10 & dose != 0)

# calculate baseline measurement pre-treatment/placebo
bc.base <- bc.sub %>% 
  filter( month >= 0 & month < 4) %>% 
  group_by(ptid) %>% 
  summarise(mean(bcarot, na.rm = T))

bc.base <- as.data.frame(bc.base)

# insert baseline measurement in place of bcarot for month "0" 
n.obs <- unlist( lapply( split( bc.sub$ptid, bc.sub$ptid ), length ) )
u.id <- unique(bc.sub$ptid)

bc.sub$base <- rep(0, nrow(bc.sub))
for(j in 1:length(u.id)){
  temp <- bc.sub %>% filter(ptid == u.id[j])
  id <- which(bc.base[,1]==u.id[j])
  row <- which(bc.sub$X == temp[1,1])
  bc.sub$base[row:(row+nrow(temp)-1)] <- rep(bc.base[id,2],nrow(temp))
}

# get rid of months 0-3
bc.sub <- bc.sub %>% filter(month != 0 & month != 1 & month != 2 & month != 3 )

sapply(bc.sub, function(x) sum(is.na(x)))
bc.sub[which(is.na(bc.sub$bcarot)),]

# replace patient 31 missing value with average of other bcarot values
# seems to be a good fit to the trend
temp <- bc.sub %>% filter(ptid == 31)
bc.sub[which(is.na(bc.sub$bcarot)),"bcarot"] <- mean(as.numeric(temp$bcarot), na.rm = T)

# no more missing values

# _____________________________________________

# AGE 
cutoffs <- summary(bc.sub$age)[c(2,4,5)]
bc.sub$agecat <- rep( 0, nrow(bc.sub) )
for( i in 1:3 ){
	bc.sub$agecat[bc.sub$age > as.numeric(cutoffs[i])] <- i
}

library(nlme)
bc.sub$agecat <- as.factor( bc.sub$agecat )
BCgrouped <- groupedData( bcarot ~ month | ptid, outer = ~ agecat, 
			data = bc.sub, labels = list(x = "Months", y = "Serum BC Levels", title = "title" ) )

# _____________________________________________

# BMI
cutoffs <- summary(bc.sub$bmi)[c(2,4,5)]
bc.sub$bmicat <- rep( 0, nrow(bc.sub) )
for( i in 1:3 ){
	bc.sub$bmicat[bc.sub$bmi > as.numeric(cutoffs[i])] <- i
}

library(nlme)
bc.sub$bmicat <- as.factor( bc.sub$bmicat )
BCgrouped <- groupedData( bcarot ~ month | ptid, outer = ~ bmicat, 
			data = bc.sub, labels = list( x = "Months", y = "Serum BC Levels") )

# _____________________________________________

# CHOLESTEROL
cutoffs <- summary(bc.sub$chol)[c(2,4,5)]
bc.sub$cholcat <- rep( 0, nrow(bc.sub) )
for( i in 1:3 ){
	bc.sub$cholcat[bc.sub$chol > as.numeric(cutoffs[i])] <- i
}

library(nlme)
bc.sub$cholcat <- as.factor( bc.sub$cholcat )
BCgrouped <- groupedData( bcarot ~ month | ptid, outer = ~ cholcat, 
			data = bc.sub, labels = list( x = "months", y = "bcarot" ) )
# _____________________________________________

path <- "~/Desktop/212/Final/"
jpeg( file=paste( path, "bmispag.jpg", sep="" ))
plot( BCgrouped, outer = ~ bmicat, aspect=2, key=FALSE )
dev.off()

path <- "~/Desktop/212/Final/"
jpeg( file=paste( path, "agespag.jpg", sep="" ))
plot( BCgrouped, outer = ~ agecat, aspect=2, key=FALSE )
dev.off()

path <- "~/Desktop/212/Final/"
jpeg( file=paste( path, "cholspag.jpg", sep="" ))
plot( BCgrouped, outer = ~ cholcat, aspect=2, key=FALSE )
dev.off()

# _____________________________________________

p.male <- ggplot() + 
  geom_point(data = bc.sub %>% filter(male == 1), aes(x=month, y=bcarot), color = "blue", alpha = 0.7) + 
  geom_smooth(data = bc.sub %>% filter(male == 1), aes(x=month, y=bcarot), color = "blue") +
  geom_point(data = bc.sub %>% filter(male == 0), aes(x=month, y=bcarot), color = "orange", alpha = 0.7) + 
  geom_smooth(data = bc.sub %>% filter(male == 0), aes(x=month, y=bcarot), color = "orange") + xlab("Month") + ylab("Serum BC Levels") + geom_text(aes(x=8, y=2250), color="orange", label = "Females") + geom_text(aes(x=8, y=2000), color="blue", label = "Males")

p.chol <- ggplot(bc.sub) +
  geom_point(aes(x=month, y=bcarot, color=cholcat)) + 
  geom_smooth(aes(x=month, y=bcarot, color=cholcat), se=F) + 
  labs( x = "Month", y = "Serum BC Levels", color = "Cholesterol \n Category \n")

p.bmi <- ggplot(bc.sub) +
  geom_point(aes(x=month, y=bcarot, color=bmicat)) + 
  geom_smooth(aes(x=month, y=bcarot, color=bmicat), se=F) + 
  labs( x = "Month", y = "Serum BC Levels", color = "BMI \n Category \n")

p.age <- ggplot(bc.sub) +
  geom_point(aes(x=month, y=bcarot, color=agecat)) + 
  geom_smooth(aes(x=month, y=bcarot, color=agecat), se=F) + 
  labs( x = "Month", y = "Serum BC Levels", color = "Age \n Category \n")

ggsave("covplot1.png", p.male)
ggsave("covplots2.png", arrangeGrob(p.chol, p.bmi, p.age))

# OBSERVATIONS
# It may be true that lower chol --> lower bcarot
# It may be true that lower BMI --> higher bcarot
# It may be true that older age --> higher bcarot
# females tend to have higher bcarot levels than males throughout the treatment phase
```

```{r fit models}
# re-number time 4-9 as 1-6
for(i in 1:nrow(bc.sub)){
  if(bc.sub$month[i] == 4) bc.sub$month[i] <- 1 
  if(bc.sub$month[i] == 5) bc.sub$month[i] <- 2 
  if(bc.sub$month[i] == 6) bc.sub$month[i] <- 3 
  if(bc.sub$month[i] == 7) bc.sub$month[i] <- 4 
  if(bc.sub$month[i] == 8) bc.sub$month[i] <- 5 
  if(bc.sub$month[i] == 9) bc.sub$month[i] <- 6 
}

# check nobs per subject
n.obs <- unlist( lapply( split( bc.sub$ptid, bc.sub$ptid ), length ) )
table(n.obs)
# get rid of subject 44 with < 3 obs
bc.sub <- bc.sub %>% filter(ptid != 44)
# now we have 35 subjects

# mean-center baseline measurement (base) in order to get a more interpretable intercept
bc.sub$mc.base <- bc.sub$base - mean(bc.sub$base)

# fit the model for male
fit.male <- gee(bcarot ~ mc.base + month*male, id = ptid, data = bc.sub, corstr = "exchangeable")
male.table <- summary(fit.male)$coeff[,c(1,4)]
plot(fit.male$fitted, fit.male$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for agecat
fit.agecat <- gee(bcarot ~ mc.base + month*agecat, id = ptid, data = bc.sub, corstr = "exchangeable")
agecat.table <- summary(fit.agecat)$coeff[,c(1,4)]
plot(fit.agecat$fitted, fit.agecat$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for age (cts)
fit.age <- gee(bcarot ~ mc.base + month*age, id = ptid, data = bc.sub, corstr = "exchangeable")
age.table <- summary(fit.age)$coeff[,c(1,4)]
plot(fit.age$fitted, fit.age$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for bmicat
fit.bmicat <- gee(bcarot ~ mc.base + month*bmicat, id = ptid, data = bc.sub, corstr = "exchangeable")
bmicat.table <- summary(fit.bmicat)$coeff[,c(1,4)]
plot(fit.bmicat$fitted, fit.bmicat$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for bmi (cts)
fit.bmi <- gee(bcarot ~ mc.base + month*bmi, id = ptid, data = bc.sub, corstr = "exchangeable")
bmi.table <- summary(fit.bmi)$coeff[,c(1,4)]
plot(fit.bmi$fitted, fit.bmi$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for cholcat
fit.cholcat <- gee(bcarot ~ mc.base + month*cholcat, id = ptid, data = bc.sub, corstr = "exchangeable")
cholcat.table <- summary(fit.cholcat)$coeff[,c(1,4)]
plot(fit.cholcat$fitted, fit.cholcat$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# fit the model for chol (cts)
fit.chol <- gee(bcarot ~ mc.base + month*I(chol/50), id = ptid, data = bc.sub, corstr = "exchangeable")
chol.table <- summary(fit.chol)$coeff[,c(1,4)]
plot(fit.chol$fitted, fit.chol$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

table <- round(cbind(male.table, chol.table, bmi.table, age.table),3)
row.names(table) <- c("Intercept", "Mc.Base", "Month", "X", "X:Month")
colnames(table) <- c("Male Est.", "Male Rob. SE", "Chol. Est.", "Chol. Rob. SE", "BMI Est.", "BMI Rob. SE", "Age Est.", "Age Rob. SE")

table2 <- round(cbind(cholcat.table, bmicat.table, agecat.table),2)
row.names(table2) <- c("Intercept", "Mc.Base", "Month", "X1", "X2","X3","X1:Month","X2:Month","X3:Month")
colnames(table2) <- c("Chol. Est.", "Chol. Robust SE", "BMI  Est.", "BMI Robust SE", "Age Est.", "Age  Robust SE")

dput(table, "cov.output")
dput(table2, "cov2.output")
```

# Question 3 - Quantify the effect of bc supplementation and impact of stopping bc supplementation on serum vit E levels over time

```{r clean data}
bc.sub <- bc[, c("X", "ptid", "month", "vite", "dose")]

# change dose to be indicator var
bc.sub$factor.dose <- rep(0, nrow(bc.sub))
for(i in 1:nrow(bc.sub)){
  if(bc.sub$dose[i] > 0) bc.sub$factor.dose[i] <- 1
}

# calculate baseline measurement pre-treatment/placebo
bc.base <- bc.sub %>% 
  filter( month >= 0 & month < 4) %>% 
  group_by(ptid) %>% 
  summarise(mean(vite, na.rm = T))

bc.base <- as.data.frame(bc.base)

# insert baseline measurement in place of vite for month "0" 
n.obs <- unlist( lapply( split( bc.sub$ptid, bc.sub$ptid ), length ) )
u.id <- unique(bc.sub$ptid)

bc.sub$base <- rep(0, nrow(bc.sub))
for(j in 1:length(u.id)){
  temp <- bc.sub %>% filter(ptid == u.id[j])
  id <- which(bc.base[,1]==u.id[j])
  row <- which(bc.sub$X == temp[1,1])
  bc.sub$base[row:(row+nrow(temp)-1)] <- rep(bc.base[id,2],nrow(temp))
}

# get rid of months 0-3
bc.sub <- bc.sub %>% filter(month != 0 & month != 1 & month != 2 & month != 3 )

sapply(bc.sub, function(x) sum(is.na(x)))
bc.sub[which(is.na(bc.sub$vite)),]

# replace patient 31 missing value with average of other vite values
# seems to be a good fit to the trend
temp <- bc.sub %>% filter(ptid == 31)
bc.sub[which(is.na(bc.sub$vite)),"vite"] <- mean(as.numeric(temp$vite), na.rm = T)

# now we have no missing values!

# let's focus on treatment and post treatment time frame
bc.sub <- bc.sub %>% filter(month > 3)
```

```{r first model EDA}
# Mean plot of Vite Response over months 4-15 stratified by treatment
p1 <- ggplot(bc.sub) +
  geom_point(aes(x=month, y=vite, color = factor(factor.dose)), alpha = 0.6) +
  geom_smooth(aes(x=month, y=vite, color = factor(factor.dose)), alpha = 0.6, se=F) + 
  geom_vline(xintercept = 9) +
  labs( x = "Month", y = "Serum Vitamin E Levels", color = "Tx \n")

# Spaghetti Plot of Vite Response over months 4-15 stratified by treatment
p2 <- ggplot() +
  geom_line(data=bc.sub %>% filter(factor.dose == 0), aes(x=month, y=vite, group=ptid), color="orangered1", alpha = 0.6) + 
  geom_line(data=bc.sub %>% filter(factor.dose == 1), aes(x=month, y=vite, group=ptid), color="violet", alpha = 0.5) + geom_vline(xintercept = 9, color = "darkgrey") +
  labs( x = "Month", y = "Serum Vitamin E Levels", color = "Tx \n") + 
  geom_text(aes(x=6, y=5), color="orangered1", label = "Placebo Group") +
  geom_text(aes(x=6, y=12.5), color="violet", label = "Treatment Group")

ggsave("vite.png", arrangeGrob(p1, p2))

sapply(bc.sub, function(x) sum(is.na(x)))
bc.sub[which(is.na(bc.sub$vite)),]

# replace patient 31 missing value with average of other vite values
# seems to be a good fit to the trend
temp <- bc.sub %>% filter(ptid == 31)
bc.sub[which(is.na(bc.sub$vite)),"vite"] <- mean(as.numeric(temp$vite), na.rm = T)
```

```{r covariance EDA}
# ONLY MONTHS 4-9 (TREATMENT MONTHS)
temp.bc <- bc.sub %>% filter(month < 10)
fit <- lm( vite ~ month, data= temp.bc)
resids <- temp.bc$vite - fitted( fit )

# variogram
out <- lda.variogram( id=temp.bc$ptid, y=resids, x=temp.bc$month )
dr <- out$delta.y
dt <- out$delta.x
var.est <- var( resids, na.rm = T )

variogram <- ggplot() +
  geom_point(aes(x=dt, y=dr), pch = ".") + 
  geom_smooth(aes(x=dt, y=dr)) + ylim(0, 1.2*var.est) + geom_hline(yintercept=var.est) + 
  ggtitle("Variogram of Plasma Vitman E Levels during Treatment Phase") + xlab("Delta Time") + ylab("Delta Residuals")

ggsave("var3.png", variogram)

# There doesn't seem to be much of a serial process; everything points to exchangeable covariance structure.
```

```{r investigate random effects}
# DURING TREATMENT PERIOD
# fits a lm for each subject
# outputs intercept and slopes
indiv.lm <- lmList( vite ~ month | ptid , data=bc.sub %>% filter(month < 10) )
plot( intervals( indiv.lm ) )
# does not seem to have strong random intercepts or slopes
```

```{r first model fit a model}
# check nobs per subject
n.obs <- unlist( lapply( split( bc.sub$ptid, bc.sub$ptid ), length ) )
table(n.obs)
# get rid of subject 44 with < 3 obs
bc.sub <- bc.sub %>% filter(ptid != 44)

# mean-center baseline measurement (base) in order to get a more interpretable intercept
bc.sub$mc.base <- bc.sub$base - mean(bc.sub$base)

# now we have 44 subjects

# DURING TREATMENT
fit <- gee(vite ~  factor.dose + mc.base + month + month*factor.dose, id = ptid, data = bc.sub %>% filter(month <10), corstr = "exchangeable")
out1 <- summary(fit)$coeff[,c(1,4)]
plot(fit$fitted, fit$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

# POST TREATMENT
fit <- gee(vite ~  factor.dose + mc.base + month + month*factor.dose, id = ptid, data = bc.sub %>% filter(month > 9), corstr = "exchangeable")
out2 <- summary(fit)$coeff[,c(1,4)]
plot(fit$fitted, fit$residuals, main="Residuals vs. Fitted Values")
abline(h=0)

table <- cbind(out1[,1],out1[,2],out2[,1],out2[,2])
row.names(table) <- c("Intercept", "Tx", "Mc.Base", "Month", "Tx:Month")
colnames(table) <- c("Tx Phase \n Estimates", "Tx Phase \n Robust SE", "Post-Tx Phase \n Estimates","Post-Tx Phase \n Robust SE")
dput(table, "vite table")
```





